apiVersion: v1
kind: Service
metadata:
  name: hello-api-stable
  labels:
    app: hello-api
    monitor: "true"
spec:
  selector: { app: hello-api }
  ports:
    - name: http
      port: 80
      targetPort: 8000
