apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: [ "{{ .Release.Namespace }}" ]
  selector:
    matchLabels:
      monitor: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
