name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps & run tests
        run: |
          pip install -r app/requirements.txt
          pytest -q

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  e2e:
    needs: test-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create KinD cluster
        uses: helm/kind-action@v1

      - name: Install kube-prometheus-stack (quick)
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install kps prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace

      - name: Deploy app with Helm
        run: |
          helm upgrade --install hello k8s/chart \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=latest

      - name: Smoke test
        run: |
          kubectl wait deploy -l app=hello-api --for=condition=available --timeout=180s || true
          kubectl get all
